# Generated by Django 4.1.2 on 2022-11-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_Edificio', models.CharField(max_length=30)),
                ('piso_Y_Letra', models.CharField(max_length=3)),
                ('cantidad_De_Ambientes', models.IntegerField()),
                ('esta_Ocupado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('cantidad_De_Pisos', models.IntegerField()),
                ('cantidad_De_Departamentos', models.IntegerField()),
                ('tiene_SUM', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('celular', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=50)),
                ('vive_En_Edificio', models.CharField(max_length=30)),
                ('vive_En_Departamento', models.CharField(max_length=3)),
            ],
        ),
    ]
