# Generated by Django 4.1.2 on 2022-11-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador_De_Edificios', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='vive_En_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador_De_Edificios.departamento'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='vive_En_Edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador_De_Edificios.edificio'),
        ),
    ]
