# Generated by Django 4.1.2 on 2022-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador_De_Edificios', '0006_alter_noticia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
            ],
        ),
    ]
