# Generated by Django 4.1.2 on 2022-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador_De_Edificios', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
